### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by devkushal23**

### CODE REVIEW

**Comment by Zero3K** [comment]
Why change Website to Site?

**Comment by devkushal23** [comment]
> Why change Website to Site?
Sir I made a change from website to site because according to latest social and internet norms site is much better form of  writing as compared to website to make common as web is made more specified. Sir it is really good change if you wnat to make otherwise as you wish you can.

**Comment by Zero3K** [comment]
Okay. Can you fix any of the issues that it has or help work on the other PR?

**Comment by devkushal23** [comment]
> Okay. Can you fix any of the issues that it has or help work on the other PR?

Ok Sir. Can you please send me oyher PRs links

**Comment by Zero3K** [comment]
Here are the pull request and issues that I would like to have fixed:

https://github.com/Zero3K/ERAM/pull/10
https://github.com/Zero3K/ERAM/issues/9
https://github.com/Zero3K/ERAM/issues/15
https://github.com/Zero3K/ERAM/issues/22

**Pull request merged**
